package gui;

import javafx.fxml.FXML;
import javafx.scene.control.ComboBox;

/**
 * ServerDatabaseAdditionController class is a controller class that handle the
 * events generated by the FXML view associated with it. It contains the logic
 * of handling the events and updating the view accordingly.
 * 
 * @FXML tablesComboBox : An instance variable that is used to store the
 *       reference to the ComboBox present in the view. This combo box is used
 *       to select the table from the database to be updated.
 * @author Rotem
 *
 */
public class ServerDatabaseAdditionController {

	@FXML
	private ComboBox<?> tablesComboBox;

}
